apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-my-app
spec:
  replicas: 2
  strategy:
    canary:
      # 트래픽을 50% 씩 30초 단위로 점진적 전환시킨다.
      steps:
        - setWeight: 50
        - pause: {duration: 30}
        - setWeight: 100
        - pause: {duration: 30}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-my-app
  template:
    metadata:
      labels:
        app: argo-my-app
    spec:
      containers:
        - name: canary-rollout-my-app
          image: how0326/marketboro:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 32Mi
              cpu: 5m