apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-my-app
spec:
  replicas: 5
  strategy:
    canary:
      maxSurge: "50%"
      maxUnavailable: 0
      steps:
        - setWeight: 25
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-my-app
  template:
    metadata:
      labels:
        app: canary-my-app
    spec:
      containers:
        - name: canary-my-app
          image: how0326/marketboro:canary
          ports:
            - containerPort: 8080