apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-my-app
spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {duration: 10}
        - setWeight: 50
        - pause: {duration: 10}
        - setWeight: 75
        - pause: {duration: 10}
        - setWeight: 100
        - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-my-app
  template:
    metadata:
      labels:
        app: argo-my-app
    spec:
      containers:
        - name: canary-rollout-my-app
          image: how0326/marketboro:canary
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 32Mi
              cpu: 5m