apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
spec:
  replicas: 5
  strategy:
    canary:
      canaryService:
      steps:
        - setWeight: 25
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-my-app
  template:
    metadata:
      labels:
        app: canary-my-app
    spec:
      containers:
        - name: canary-my-app
          image: how0326/marketboro:canary
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: secret-configs
            - configMapRef:
                name: configs