apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: ma-app
    spec:
      containers:
        - name: my-app
          image: how0326/marketboro:latest
          ports:
            - name: tcp
              containerPort: 8080