apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-my-app
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/service
    repoURL: git@github.com:seongwoo-choi/marketboro.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true