apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: canary-my-app
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  type: LoadBalancer