apiVersion: v1
kind: Service
metadata:
  name: canary-service
  annotations:
    kubernetes.io/ingress.class: external
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: canary-my-app
  type: LoadBalancer