#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: my-app-deployment
#  labels:
#    app: my-app
#spec:
#  replicas: 4
#  selector:
#    matchLabels:
#      app: my-app
#  template:
#    metadata:
#      labels:
#        app: my-app
#    spec:
#      containers:
#        - name: my-app
#          image: how0326/marketboro:8
#          envFrom:
#            - secretRef:
#                name: secret-configs
#            - configMapRef:
#                name: configs
#          ports:
#            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /api/health
#              port: 8080
#            initialDelaySeconds: 20
#            periodSeconds: 10
#            successThreshold: 1
#            timeoutSeconds: 10
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: /api/health
#              port: 8080
#            initialDelaySeconds: 20
#            periodSeconds: 10
#            successThreshold: 1
#            failureThreshold: 5
#            timeoutSeconds: 10